version: "3.8"
services:
    mysql:
        image: mysql:8
        container_name: lana-mysql
        working_dir: /lana
        volumes:
            - ./:/lana
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=lana_blog
        ports:
            - 16122:3306
        restart: unless-stopped

    nginx:
        build: docker/nginx
        container_name: lana-nginx
        user: root
        working_dir: /lana
        volumes:
            - ./:/lana
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 16123:80
        depends_on:
            - php-fpm
        restart: unless-stopped

    redis:
        image: redis:alpine
        container_name: lana-redis
        restart: unless-stopped

    php-fpm:
        build: docker/php-fpm
        container_name: lana-php
        working_dir: /lana
        ports:
            - 6007:6007
        volumes:
            - ./:/lana
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
        depends_on:
            - mysql
        restart: unless-stopped

volumes:
    pgdata:
    mysql:
    db:

    # networks:
    #   default:
    #     driver: bridge
    # second_default:
    #   external: true
